packages:
  - internal/*
  - internal/lint-configs/*
  - packages/*
  - packages/@core/base/*
  - packages/@core/ui-kit/*
  - packages/@core/forward/*
  - packages/@core/*
  - packages/effects/*
  - packages/business/*
  - apps/*
  - scripts/*
  - docs
  - playground

catalog:
  '@antfu/eslint-config': ^4.11.0
  '@ast-grep/napi': ^0.39.9
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.7
  '@changesets/git': ^3.0.4
  '@clack/prompts': ^0.11.0
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@ctrl/tinycolor': ^4.1.0
  '@eslint/js': ^9.39.1
  '@faker-js/faker': ^9.9.0
  '@fastify/cookie': ^11.0.2
  '@fastify/multipart': ^9.0.3
  '@fastify/static': ^8.1.1
  '@iconify/json': ^2.2.406
  '@iconify/tailwind': ^1.2.0
  '@iconify/vue': ^5.0.0
  '@intlify/core-base': ^11.1.7
  '@intlify/unplugin-vue-i18n': ^6.0.8
  '@jspm/generator': ^2.6.2
  '@manypkg/get-packages': ^3.0.0
  '@nestjs/axios': ^4.0.0
  '@nolebase/vitepress-plugin-git-changelog': ^2.18.0
  '@playwright/test': ^1.56.1
  '@pnpm/workspace.read-manifest': ^1000.2.6
  '@stylistic/stylelint-plugin': ^3.1.3
  '@tailwindcss/nesting': 0.0.0-insiders.565cd3e
  '@tailwindcss/typography': ^0.5.16
  '@tanstack/vue-query': ^5.91.0
  '@tanstack/vue-store': ^0.8.0
  '@types/archiver': ^6.0.3
  '@types/eslint': ^9.6.1
  '@types/html-minifier-terser': ^7.0.2
  '@types/json-bigint': ^1.0.4
  '@types/jsonwebtoken': ^9.0.10
  '@types/jest': ^29.5.14
  '@types/lodash': ^4.17.16
  '@types/lodash.clonedeep': ^4.5.9
  '@types/lodash.get': ^4.4.9
  '@types/lodash.isequal': ^4.5.8
  '@types/lodash.set': ^4.3.9
  '@types/multer': ^1.4.12
  '@types/node': ^24.10.1
  '@types/nprogress': ^0.2.3
  '@types/passport-jwt': ^4.0.1
  '@types/postcss-import': ^14.0.3
  '@types/qrcode': ^1.5.5
  '@types/qs': ^6.14.0
  '@types/sortablejs': ^1.15.8
  '@types/supertest': ^6.0.3
  '@types/ua-parser-js': ^0.7.39
  '@typescript-eslint/eslint-plugin': ^8.46.4
  '@typescript-eslint/parser': ^8.46.4
  '@vee-validate/zod': ^4.15.1
  '@vite-pwa/vitepress': ^1.0.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitejs/plugin-vue-jsx': ^5.1.1
  '@vue/reactivity': ^3.5.17
  '@vue/shared': ^3.5.24
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^13.4.0
  '@vueuse/integrations': ^14.0.0
  '@vueuse/motion': ^3.0.3
  ant-design-vue: ^4.2.6
  archiver: ^7.0.1
  autoprefixer: ^10.4.22
  axios: ^1.10.0
  axios-mock-adapter: ^2.1.0
  bull: ^4.16.5
  cache-manager: ^6.4.2
  cac: ^6.7.14
  chalk: ^5.4.1
  cheerio: ^1.1.0
  circular-dependency-scanner: ^2.3.0
  class-transformer: ^0.5.1
  class-validator: ^0.14.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commitlint-plugin-function-rules: ^4.1.1
  consola: ^3.4.2
  cross-env: ^7.0.3
  cron: ^4.1.4
  cron-parser: ^5.1.1
  crypto-js: ^4.2.0
  cspell: ^8.19.4
  cssnano: ^7.0.7
  cz-git: ^1.11.2
  czg: ^1.11.1
  dayjs: ^1.11.13
  defu: ^6.1.4
  depcheck: ^1.4.7
  dotenv: ^16.6.1
  echarts: ^6.0.0
  element-plus: ^2.10.2
  eslint: ^9.39.1
  eslint-config-turbo: ^2.6.1
  eslint-plugin-command: ^3.3.1
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-jsdoc: ^61.2.1
  eslint-plugin-jsonc: ^2.21.0
  eslint-plugin-n: ^17.23.1
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.15.1
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-regexp: ^2.10.0
  eslint-plugin-unicorn: ^62.0.0
  eslint-plugin-unused-imports: ^4.3.0
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^10.5.1
  execa: ^9.6.0
  find-up: ^7.0.0
  get-port: ^7.1.0
  globals: ^16.3.0
  h3: ^1.15.3
  handlebars: ^4.7.8
  happy-dom: ^17.6.3
  helmet: ^8.1.0
  html-minifier-terser: ^7.2.0
  ioredis: ^5.6.0
  is-ci: ^4.1.0
  jest: ^29.7.0
  jiti: ^2.6.1
  json-bigint: ^1.0.0
  jsonc-eslint-parser: ^2.4.1
  jsonwebtoken: ^9.0.2
  lefthook: ^1.13.6
  lint-staged: ^15.5.0
  lodash: ^4.17.21
  lodash.clonedeep: ^4.5.0
  lodash.get: ^4.4.2
  lodash.isequal: ^4.5.0
  lodash.set: ^4.3.2
  lucide-vue-next: ^0.553.0
  medium-zoom: ^1.1.0
  mysql2: ^3.14.0
  nanoid: ^3.3.7
  naive-ui: ^2.42.0
  nestjs-cls: ^5.4.2
  nitropack: ^2.11.13
  nodemailer: ^6.10.0
  nprogress: ^0.2.0
  ora: ^8.2.0
  passport: ^0.7.0
  passport-google-oauth20: ^2.0.0
  passport-jwt: ^4.0.1
  passport-local: ^1.0.0
  pinia: ^3.0.3
  pinia-plugin-persistedstate: ^4.4.1
  pkg-types: ^2.2.0
  playwright: ^1.56.1
  postcss: ^8.5.6
  postcss-antd-fixes: ^0.2.0
  postcss-html: ^1.8.0
  postcss-import: ^16.1.1
  postcss-preset-env: ^10.2.4
  postcss-scss: ^4.0.9
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.7.1
  publint: ^0.3.12
  qiniu: ^7.14.0
  qrcode: ^1.5.4
  qs: ^6.14.0
  reka-ui: ^2.6.0
  reflect-metadata: ^0.2.2
  resolve.exports: ^2.0.3
  rimraf: ^6.1.0
  rollup: ^4.44.1
  rollup-plugin-visualizer: ^5.14.0
  rxjs: ^7.8.2
  sass: ^1.94.0
  secure-ls: ^2.0.0
  simple-git-hooks: ^2.12.1
  socket.io: ^4.8.1
  sortablejs: ^1.15.6
  source-map-support: ^0.5.21
  stacktrace-js: ^2.0.2
  stylelint: ^16.21.0
  stylelint-config-recess-order: ^6.1.0
  stylelint-config-recommended: ^17.0.0
  stylelint-config-recommended-scss: ^14.1.0
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^38.0.0
  stylelint-order: ^7.0.0
  stylelint-prettier: ^5.0.3
  stylelint-scss: ^6.12.1
  supertest: ^7.1.0
  svg-captcha: ^1.4.0
  systeminformation: ^5.25.11
  tailwind-merge: ^2.6.0
  tailwindcss: ^3.4.18
  tailwindcss-animate: ^1.0.7
  tdesign-vue-next: ^1.17.1
  theme-colors: ^0.1.0
  tippy.js: ^6.3.7
  ts-jest: ^29.3.1
  ts-loader: ^9.5.2
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  tsx: ^4.19.3
  turbo: ^2.6.1
  typeorm: ^0.3.22
  typescript: ^5.9.3
  ua-parser-js: ^2.0.3
  unbuild: ^3.6.1
  unplugin-element-plus: ^0.11.1
  vee-validate: ^4.15.1
  vite: ^7.2.2
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-html: ^3.2.2
  vite-plugin-lazy-import: ^1.0.7
  vite-plugin-pwa: ^1.0.1
  vite-plugin-vue-devtools: ^8.0.3
  vitepress: ^1.6.3
  vitepress-plugin-group-icons: ^1.6.1
  vitest: ^3.2.4
  vue: ^3.5.24
  vue-eslint-parser: ^10.2.0
  vue-i18n: ^11.1.7
  vue-json-viewer: ^3.0.4
  vue-router: ^4.5.1
  vue-tippy: ^6.7.1
  vue-tsc: ^3.1.4
  vxe-pc-ui: ^4.10.22
  vxe-table: ^4.17.14
  watermark-js-plus: ^1.6.2
  winston: ^3.17.0
  winston-daily-rotate-file: ^5.0.0
  zod: ^3.25.67
  zod-defaults: 0.1.3
  es-toolkit: ^1.41.0
  '@liaoliaots/nestjs-redis': ^10.0.0
  '@nestjs-modules/mailer': ^2.0.2
  '@nestjs/bull': ^11.0.2
  '@nestjs/cache-manager': ^3.0.1
  '@nestjs/common': ^11.0.13
  '@nestjs/config': ^4.0.2
  '@nestjs/core': ^11.0.13
  '@nestjs/event-emitter': ^3.0.1
  '@nestjs/jwt': ^11.0.0
  '@nestjs/passport': ^11.0.5
  '@nestjs/platform-fastify': ^11.0.13
  '@nestjs/platform-socket.io': ^11.0.13
  '@nestjs/schedule': ^5.0.1
  '@nestjs/swagger': ^11.1.1
  '@nestjs/terminus': ^11.0.0
  '@nestjs/throttler': ^6.4.0
  '@nestjs/typeorm': ^11.0.0
  '@nestjs/websockets': ^11.0.13
  '@socket.io/redis-adapter': ^8.3.0
  '@socket.io/redis-emitter': ^5.1.0
  'cache-manager-ioredis-yet': ^2.1.2
  '@compodoc/compodoc': ^1.1.26
  '@nestjs/cli': ^11.0.6
  '@nestjs/schematics': ^11.0.3
  '@nestjs/testing': ^11.0.13
  '@types/cache-manager': ^4.0.6
